--
-- Скрипт сгенерирован Devart dbForge Studio for MySQL, Версия 8.0.80.0
-- Домашняя страница продукта: http://www.devart.com/ru/dbforge/mysql/studio
-- Дата скрипта: 15.09.2018 15:38:48
-- Версия сервера: 5.5.58-log
-- Версия клиента: 4.1
--


SET NAMES 'utf8';

INSERT INTO newyear.sys_urls(row_id, phpfile, scrip, template, parent, independ, label, level, address, h1, menu, title, keywords, description, noindex, access, `virtual`, header, comments, slash) VALUES
(1, 'php/php_platmain.php', ' ', 'bscwarn', NULL, NULL, 'plat', NULL, 'enter', 'процессинговая система', '', 'Денис Дроздецкий++', 'Ключевые слова страницы Движок', 'Описание страницы Движок', 0, 0, 0, '', 0, NULL),
(104, 'php/data_data.php', NULL, 'plain', NULL, NULL, 'data', NULL, 'data', 'обмен данными', '', 'Обмен данными', 'Ключевые слова страницыОбмен данными', 'Описание страницы Обмен данными', 0, 0, 0, 'Content-Type: text/plain; charset=utf-8', 0, NULL),
(3, 'php/data_test.php', ' ', 'bscwarn', NULL, NULL, 'test', 1, 'Тест', '', '', 'Тестовая страница', 'Ключевые слова страницы', 'Описание страницы ', 0, 0, 0, '', 1, NULL),
(4, 'php/data_test2.php', ' ', 'standart', 'test8', NULL, 'test2', 1, 'Проба 2', '', '', '+Пробная страница №2', '+Ключевые слова страницыПробная страница №2', '+Описание страницы Пробная страница №2', 0, 0, 0, '', 0, NULL),
(5, 'php/data_test3.php', ' ', 'bscwarn', 'test9', NULL, 'test3', 1, 'Проба 3', '123', '', 'Проба №3 - ', 'Ключевые слова страницы Движок', 'Описание страницы Движок jgfjcjh', 0, 0, 0, '', 0, NULL),
(8, 'php/data_post.php', ' ', 'plain', NULL, NULL, 'post', NULL, 'post', '', '', 'Обработка POST переменных', 'Ключевые слова страницыОбработка POST переменных', 'Описание страницы Обработка POST переменных', 0, 0, 0, '', 0, NULL),
(10, 'php/data_admin.php', NULL, 'bscwarn', NULL, NULL, 'admin', NULL, 'Администратор/Назначения', '', '', 'Рабочее место администратора', 'Ключевые слова страницыРабочее место администратора', 'Описание страницы Рабочее место администратора', 0, 2, 0, '', 0, NULL),
(12, 'php/data_login.php', ' ', 'bscwarn', NULL, NULL, 'login', NULL, 'Логин', '', '', 'Молви друг и входи', 'Ключевые слова страницыМолви друг и входи', 'Описание страницы Молви друг и входи', 0, 0, 0, '', 0, NULL),
(14, 'php/data_admuseradd.php', NULL, 'bscwarn', NULL, NULL, 'admusadd', NULL, 'Администратор/Добавить пользователя', '', '', 'Рабочее место администратора - Добавление пользователя', 'Ключевые слова страницыРабочее место администратора - Добавление пользователя', 'Описание страницы Рабочее место администратора - Добавление пользователя', 0, 2, 0, '', 0, NULL),
(15, 'php/data_admusedit.php', NULL, 'bscwarn', NULL, NULL, 'admusedit', 1, 'Пользователи', '', '', 'Рабочее место менеджера - Изменение пользователя', 'Ключевые слова страницыРабочее место менеджера - Изменение пользователя', 'Описание страницы Рабочее место менеджера - Изменение пользователя', 0, 2, 0, '', 0, NULL),
(23, 'php/data_adm.php', NULL, 'bscwarn', NULL, NULL, 'adm', NULL, 'Администратор', '', '', 'Рабочее место администратора', 'Ключевые слова страницы Рабочее место администратора', 'Описание страницы Рабочее место администратора', 0, 2, 0, '', 0, NULL),
(25, 'php/data_engine.php', ' ', 'finance1', NULL, NULL, 'engine', 1, 'engine', '', '', 'Движок', 'Ключевые слова страницы Движок', 'Описание страницы Движок', 1, 2, 0, '', 0, NULL),
(46, 'php/data_chpuadd.php', ' ', 'bscwarn', NULL, NULL, 'chpuadd', NULL, 'engine/add url', '', '', 'Добавление раздела', 'Ключевые слова страницы Добавление раздела', 'Описание страницы Добавление раздела', 0, 2, 0, '', 0, NULL),
(48, 'php/data_scriptedit.php', ' ', 'bscwarn', NULL, NULL, 'scriptedit', 1, 'scriptedit', NULL, NULL, 'Движок', 'Ключевые слова страницы Движок', 'Описание страницы Движок', NULL, 2, NULL, NULL, 0, NULL),
(49, 'php/data_scriptadd.php', ' ', 'bscwarn', NULL, NULL, 'scriptadd', NULL, 'scriptadd', '123', NULL, 'Добавление скрипта', 'Ключевые слова страницы Движок', 'Описание страницы Движок', 0, 2, NULL, '', 0, NULL),
(50, '', 'addpict', 'bscwarn', NULL, NULL, 'addpicture', NULL, 'addpicture', '', '', 'Движок', 'Ключевые слова страницы Движок', 'Описание страницы Движок', 0, 0, 0, '', 0, NULL),
(51, '', 'addpicproc', 'bscwarn', NULL, NULL, 'addpicproc', NULL, 'addpicproc', '', '', 'обработка картинки', 'Ключевые слова страницы обработка картинки', 'Описание страницы обработка картинки', 0, 0, 0, '', 0, NULL),
(52, 'php/data_test_wiki.php', 'test', 'bscwarn', 'test8', NULL, 'wiki', 1, 'вики', '', '', 'Вики+', 'Ключевые слова страницы Вики', 'Описание страницы Вики', 0, 0, 0, '', 0, NULL),
(53, 'php/data_catal.php', ' ', 'bscwarn', NULL, NULL, 'catal', NULL, 'Каталог', '', '', 'Каталог', 'Ключевые слова страницы Каталог', 'Описание страницы Каталог', 0, 0, 0, '', 0, NULL),
(54, 'php/data_404.php', ' ', 'bscwarn', NULL, NULL, '404', NULL, '404', '404', '', 'Движок', 'Ключевые слова страницы Движок', 'Описание страницы Движок', 0, 0, 0, '', 0, NULL),
(55, 'amazon/data_amazon.php', NULL, 'bscwarn', NULL, NULL, 'amazon', NULL, 'amaz', '', '', 'Amazon', 'Ключевые слова страницы Amazon', 'Описание страницы Amazon', 0, 0, 0, '', 0, NULL),
(56, 'php/data_test4.php', ' ', 'bscwarn', NULL, NULL, 'test4', NULL, 'Проба 4', '321', '', 'Тест 4 ++', 'Ключевые слова тест 4', 'Описание страницы Движок', 0, 2, 0, '', 0, NULL),
(57, 'php/data_elrte.php', ' ', 'clrte', NULL, NULL, 'elrte', 1, 'редактор', NULL, NULL, 'Движок', 'Ключевые слова страницы Движок', 'Описание страницы Движок', NULL, 2, NULL, NULL, 0, NULL),
(60, 'php/data_xml.php', ' ', 'plain', NULL, NULL, 'test_xml', NULL, 'test xml', 'Тест XML', '', 'Движок', 'Ключевые слова страницы Движок', 'Описание страницы Движок', 0, 0, 0, 'Content-Type: text/xml\r\nLast-Modified: &quot;.gmdate(&quot;D, d M Y H:i:s&quot;).&quot; GMT\r\nCache-Control: no-cache, must-revalidate\r\nCache-Control: post-check=0,pre-check=0\r\nCache-Control: max-age=0\r\nPragma: no-cache', 0, NULL),
(61, 'php/test_redis.php', ' ', 'bscwarn', NULL, NULL, 'test_redis', NULL, 'test redis', 'Тест Redis', '', 'Redis', 'Ключевые слова страницы Движок', 'Описание страницы Redis', 0, 0, 0, '', 0, NULL),
(62, '', 'phpinfo', 'bscwarn', NULL, NULL, 'phpinfo', NULL, 'php info', '', '', 'Движок', 'Ключевые слова страницы Движок', 'Описание страницы Движок', 0, 0, 0, '', 0, NULL),
(64, '', 'pagintest', 'bscwarn', NULL, NULL, 'pagin', 1, 'Проба пагинатора', '', NULL, 'Пагинатор', 'Ключевые слова страницы Движок', 'Описание страницы Движок', 1, 0, NULL, '', 0, NULL),
(65, 'php/test_sqlite.php', '', 'bscwarn', NULL, NULL, 'sqlite', NULL, 'test sqlite', '', NULL, 'SQLite', 'Ключевые слова страницы Добавление раздела', 'Описание страницы Добавление раздела', NULL, 0, NULL, '', 0, NULL),
(66, 'php/data_wysiwyg.php', ' ', 'bscwarnck', NULL, NULL, 'wysiwyg', 1, 'wysiwyg', '', NULL, 'Редактор', 'Редактор', 'Редактор', 1, 2, NULL, '', 0, 1),
(70, 'php/php_ckupload.php', ' ', 'plain', NULL, NULL, 'ckupload', NULL, 'ckupload', NULL, NULL, 'upload', 'Ключевые слова страницы upload', 'Описание страницы upload', 0, 0, NULL, NULL, 0, 1),
(71, 'php/php_ckbrowse.php', ' ', 'simple', NULL, NULL, 'ckbrowse', NULL, 'ckbrowse', '', NULL, 'ckbrowse', 'Ключевые слова страницы ckbrowse', 'Описание страницы ckbrowse', 0, 0, NULL, '', 0, NULL),
(72, '/kcfinder/browse.php', '', 'plain', NULL, NULL, 'filebrowser', NULL, 'filebrowser', '', NULL, '', '', '', NULL, 0, NULL, '', 0, NULL),
(73, 'php/data_test7.php', ' ', 'bscwarn', NULL, NULL, 'test7', 1, 'Проба 7', '', NULL, 'Дежурные пробы на разные темы', 'Ключевые слова страницы Добавление раздела', 'Описание страницы Добавление раздела', 0, 0, NULL, '', 2, NULL),
(74, '', 'dyatpear', 'plain', NULL, NULL, 'dyatpear', NULL, 'dyatpear', '', NULL, '', '', '', 0, 0, NULL, 'Content-Type: image/png', 0, NULL),
(77, '', ' ', 'test', NULL, NULL, 'profile', 1, 'Профиль', '', NULL, 'Личное дело Штирлица Отто фон', 'Ключевики профайла', 'Профайл юзера', 0, 0, NULL, '', 0, NULL),
(78, 'php/php_tinymce.php', ' ', 'bscwarnck', NULL, NULL, 'tinymce', 1, 'edithtml', '', NULL, 'Редактор', 'Редактор', 'Редактор', 1, 2, NULL, '', 0, NULL),
(79, 'php/data_test8.php', ' ', 'bscwarn', NULL, NULL, 'test8', NULL, 'Проба 8', '', NULL, 'Проба 8', 'Проба 8', 'Проба 8', 0, 0, NULL, '', 1, NULL),
(80, 'php/data_test9.php', ' ', 'bscwarn', 'test8', NULL, 'test9', NULL, 'Проба 9', '', NULL, 'Проба 9', 'Проба 9', 'Проба 9', 0, 0, NULL, '', 1, 1),
(81, 'php/data_test10.php', ' ', 'bscwarn', 'test9', NULL, 'test10', NULL, 'Проба 10', '', NULL, 'Проба 10', 'Проба 10', 'Проба 10', 0, 0, NULL, '', 1, NULL),
(82, 'php/data_test_partial.php', ' ', 'bscwarn', 'test10', NULL, 'testpartial', NULL, 'Проба Partial', '', NULL, 'Проба Partial', 'Проба Partial', 'Проба Partial', 0, 0, NULL, '', 1, NULL),
(84, '', 'tesst', 'bscwarn', 'test11', 1, 'test89', NULL, 'Проба 8/Проба 0', '', NULL, 'Проба 8-9', 'Проба 8-9', 'Проба 8-9', 0, 0, NULL, '', 1, 0),
(85, '', 'testecho', 'plain', NULL, NULL, 'testecho', NULL, 'testecho', '', NULL, 'Проба echo', 'Проба echo', 'Проба echo', 0, 0, NULL, '''Content-Type: text/html; charset=utf-8', 0, NULL),
(86, '', 'tesst', 'bscwarn', 'test8', NULL, 'testhtm', NULL, 'file.html', '', NULL, 'Test html', 'Test html', 'Test html', 0, 0, NULL, '', 0, NULL),
(88, 'php/php_editmes.php', '', 'bscwarn', NULL, NULL, 'editmes', 1, 'editmes', '', NULL, 'Правка', 'Правка', 'Правка', NULL, 0, NULL, '', 0, NULL),
(199, 'php/test/test_stat1.php', ' ', 'bscwarn', NULL, NULL, 'stat1', 1, 'stat1', '123', '', '', '', '', 0, 0, 0, '', 0, NULL),
(196, 'php/test/test_curl.php', NULL, 'bscwarn', NULL, NULL, 'testcurl', NULL, 'testcurl', NULL, NULL, 'Test cURL', NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL),
(91, 'php/data_post.php', NULL, 'plain', NULL, NULL, 'forumpost', NULL, 'post', '', '', 'Обработка POST переменных', 'Ключевые слова страницыОбработка POST переменных', 'Описание страницы Обработка POST переменных', 0, 0, 0, '', 0, NULL),
(93, 'php/data_xml2.php', ' ', 'plain', NULL, NULL, 'test_xml2', NULL, 'test xml2', 'Тест XML', '', 'Движок', 'Ключевые слова страницы Движок', 'Описание страницы Движок', 0, 0, 0, '', 0, NULL),
(94, 'php/test_testpost.php', ' ', 'flow', NULL, NULL, 'test_post', 1, 'Проба пост', '', NULL, 'FLowers', '', '', 0, 0, NULL, '', 0, NULL),
(95, 'php/test_testpost2.php', ' ', 'flow', 'biko1', NULL, 'test_post2', NULL, 'Проба пост2', '', NULL, '', '', '', 0, 0, NULL, '', 0, NULL),
(97, 'php/test_testpost3.php', ' ', 'flow', 'biko1', NULL, 'test_post3', NULL, 'Проба пост3', '', NULL, '', '', '', 0, 0, NULL, '', 0, NULL),
(98, 'php/php_forms.php', ' ', 'flow', '', NULL, 'forms', NULL, 'forms', '', NULL, 'Формы', 'Формы', 'Формы', 0, 0, NULL, '', 0, NULL),
(100, '', '', 'bscwarn', NULL, NULL, 'razd', NULL, 'Раздел для пробы', '', NULL, '111111', '22222', '33333333', NULL, 0, NULL, '', 0, NULL),
(101, '', 'main2', 'bscwarn', NULL, NULL, 'main2', NULL, '22', 'процессинговая система', '', '', '', '', 0, 0, 0, '', 0, NULL),
(102, 'php/testform.php', '', 'bscwarn', NULL, NULL, 'testform', NULL, 'testform', 'процессинговая система', '', 'Титул', '', '', 0, 0, 0, '', 0, NULL),
(2, '', 'nyabout', 'ny4main', NULL, NULL, 'main', 1, '', 'Новогодние игрушки ручной работы', '', 'Winter Trees Новогодние игрушки ручной работы, оформление рождественских елок', 'Winter Trees, Новогодние игрушки,', 'Winter Trees Новогодние игрушки ручной работы, оформление рождественских елок', 0, 0, 0, '', 0, NULL),
(103, 'php/test_activmenu.php', '', 'navyellow', NULL, NULL, 'test01', NULL, 'Пробный 01', 'процессинговая система', '', '', '', '', 0, 0, 0, '', 0, NULL),
(194, 'php/test/test_curldata.php', NULL, 'bscwarn', NULL, NULL, 'testcurldata', NULL, 'testcurldata', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL),
(195, 'php/test/test_getpost.php', NULL, 'plain', NULL, NULL, 'testgetpost', NULL, 'testgetpost', NULL, NULL, 'Test GET/POST', NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL),
(197, 'php/test/test_soap.php', NULL, 'bscwarn', NULL, NULL, 'testsoap', NULL, 'testsoap', NULL, NULL, 'Test SOAP', NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL),
(198, 'php/data_test3.php', ' ', 'bscwarn', 'test9', NULL, 'test3', 1, 'Проба 3', '123', '', '', '', '', 0, 0, 0, '', 0, NULL),
(200, 'php/test/test_stat2.php', ' ', 'bscwarn', NULL, NULL, 'stat2', 1, 'stat2', '123', '', '', '', '', 0, 0, 0, '', 0, NULL),
(260, 'php/handy/php_login.php', ' ', 'tlogboot', NULL, NULL, 'ttlogin', NULL, '2tlogin', 'логин', '', 'Вход', 'Логин', '', 0, 0, 0, '', 0, NULL),
(263, 'php/system/php_graph.php', ' ', 'bscwarncanv', NULL, NULL, 'graph', 1, 'Графы', '', '', 'Графы', '', '', 0, 0, 0, '', 0, NULL),
(201, 'php/handy/ajax_infhistory.php', NULL, 'plain', NULL, NULL, 'ajxhistory', NULL, 'ajaxpsohistory', 'История операций PSO', '', '', 'Keywords', 'Description', 0, 0, 0, '', 0, NULL),
(262, 'php/system/php_getpost.php', ' ', 'flow', NULL, NULL, 'getpost', 1, 'getpost', '', '', '', '', '', 0, 0, 0, '', 0, NULL),
(264, 'php/system/php_svg.php', ' ', 'bscwarn', NULL, NULL, 'svg', 1, 'svg', '', '', 'SVG', '', '', 0, 0, 0, '', 0, NULL),
(266, 'php/test/test_db.php', ' ', 'bscwarn', NULL, NULL, 'testdb', 1, 'testdb', '', '', 'Новый ДБ двиг', '', '', 0, 0, 0, '', 0, NULL),
(257, 'php/handy/ajax_celloper.php', NULL, 'plain', NULL, NULL, 'ajxcelloper', NULL, 'ajaxcelloper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL),
(258, 'php/test/test_loadcont.php', ' ', 'ny4', NULL, NULL, 'testloadcont', 1, 'test load cont', 'test load cont', NULL, 'Тест load_cont()', '', '', 0, 0, NULL, '', 0, NULL),
(259, 'php/handy/php_javascript.php', NULL, 'plain', NULL, NULL, 'templejs', NULL, 'assets/scripts/master.js', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Content-Type: text/plain; charset=utf-8', 0, NULL),
(261, 'php/GeoIp2/max.php', ' ', 'bscgeo', NULL, NULL, 'geoip', 1, 'geoip', '123', '', '', '', '', 0, 0, 0, '', 0, NULL),
(267, 'php/depo/php_reg.php', ' ', 'tmain2boot', NULL, NULL, 'reg', NULL, 'register', '', NULL, 'Регистрация', 'Регистрация', '', 0, 0, NULL, '', 0, NULL),
(268, 'php/depo/php_users.php', '', 'tmain2boot', NULL, NULL, 'userlist', 1, 'userlist', '', NULL, 'Зарегистрированные пользователи', 'Зарегистрированные пользователи', 'Зарегистрированные пользователи', NULL, 0, NULL, '', 0, NULL),
(269, 'php/depo/php_login.php', ' ', 'tmain2boot', NULL, NULL, 'userlogin', NULL, 'login', 'логин', '', 'Вход', 'Логин', '', 0, 0, 0, '', 0, NULL),
(275, 'php/test/test_buf.php', NULL, 'tmain2boot', NULL, NULL, 'testbuf', NULL, 'testbuf', NULL, NULL, 'PHP Protocol Buffers', 'PHP Protocol Buffers', 'PHP Protocol Buffers', NULL, NULL, NULL, NULL, 0, NULL),
(276, 'php/depo/php_users.php', '', 'tmain2boot', NULL, NULL, 'filledusers', 1, 'filledusers', '', NULL, 'Зарегистрированные пользователи', 'Зарегистрированные пользователи', 'Зарегистрированные пользователи', NULL, 0, NULL, '', 0, NULL),
(277, 'php/test/test_twcms.php', '', 'tmain2boot', NULL, NULL, 'twcmstest', NULL, 'twcmstest', '', NULL, 'TWCMS', 'TWCMS', 'TWCMS', NULL, 0, NULL, '', 0, NULL),
(278, 'php/depo/php_enter.php', '', 'finance0', NULL, NULL, 'enter', NULL, 'Авторизация', '', NULL, 'Авторизация', 'Авторизация', 'Авторизация', NULL, 0, NULL, '', 0, NULL),
(281, 'php/depo/php_recharge.php', '', 'finance1', NULL, NULL, 'recharge', 1, 'Пополнение', '', NULL, 'Пополнение', 'Пополнение', 'Пополнение', NULL, 0, NULL, '', 0, NULL),
(279, 'php/depo/php_entrance.php', '', 'tmain4boot', NULL, NULL, 'entrance', NULL, 'Вход', '', NULL, 'Вход', 'Вход', 'Вход', NULL, 0, NULL, '', 0, NULL),
(280, 'php/depo/php_cabin.php', '', 'tmain6boot', NULL, NULL, 'cabin', NULL, 'Кабинет', '', NULL, 'Личный Кабинет', 'Личный Кабинет', 'Личный Кабинет', NULL, 0, NULL, '', 0, NULL),
(282, 'php/depo/php_requests.php', '', 'tmain6boot', NULL, NULL, 'requests', NULL, 'Заявки', '', NULL, 'Запросы', 'Запросы', 'Запросы', NULL, 0, NULL, '', 0, NULL),
(283, 'php/depo/php_products.php', '', 'tmain6boot', NULL, NULL, 'products', NULL, 'Продукты', '', NULL, 'Продукты', 'Продукты', 'Продукты', NULL, 0, NULL, '', 0, NULL),
(284, 'php/depo/php_accts.php', '', 'finance1', NULL, NULL, 'personal', NULL, 'Персональный кабинет', '', NULL, 'Личный Кабинет', 'Личный Кабинет', 'Личный Кабинет', NULL, 1, NULL, '', 0, NULL),
(285, 'php/depo/php_getbackofficeinfo.php', '', 'tmain5boot', NULL, NULL, 'contracts', NULL, 'Договоры', '', NULL, 'Договоры', 'Договоры', 'Договоры', NULL, 1, NULL, '', 0, NULL),
(286, 'php/depo/php_universal.php', '', 'tmain5boot', NULL, NULL, 'universal', NULL, 'Пробный кабинет', '', NULL, 'Пробный Кабинет', 'Пробный Кабинет', 'Пробный Кабинет', NULL, 1, NULL, '', 0, NULL),
(287, 'php/depo/php_cabinet.php', '', 'finance1', NULL, NULL, 'cabinet', NULL, 'Личный кабинет', '', NULL, 'Личный Кабинет', 'Личный Кабинет', 'Личный Кабинет', NULL, 1, NULL, '', 0, NULL),
(288, 'php/depo/php_refill.php', '', 'tmain5boot', NULL, NULL, 'refill', 1, 'Пополнить', '', NULL, 'Пополнение', 'Пополнение', 'Пополнение', NULL, 1, NULL, '', 0, NULL),
(289, 'php/newyear/php_gallery.php', ' ', 'ny4', NULL, NULL, 'gallery', 1, 'Галерея', '', '', 'Галерея', 'Галерея', 'Галерея', 0, 0, 0, '', 0, NULL),
(290, 'php/newyear/php_order.php', '', 'ny4', NULL, NULL, 'nyorder', 1, 'Заказать', '', '', 'Заказть', 'Галерея', 'Галерея', 0, 0, 0, '', 0, NULL),
(291, 'php/newyear/php_ordlist.php', '', 'ny4', NULL, NULL, 'nyordlist', NULL, 'Список заказов', '', '', 'Список заказов', 'Список заказов', 'Список заказов', 0, 1, 0, '', 0, NULL),
(292, '', 'nycont', 'ny4', NULL, NULL, 'nycont', 1, 'Контакты', '', NULL, 'Контакты', 'Контакты', 'Контакты', 0, 0, NULL, '', 0, NULL);