CREATE TABLE sys_urls (
  id int(11) NOT NULL,
  path varchar(75) DEFAULT NULL,
  scrip varchar(75) DEFAULT NULL,
  template varchar(75) DEFAULT NULL,
  parent varchar(64) DEFAULT NULL,
  independ tinyint(3) DEFAULT NULL,
  label varchar(64) DEFAULT NULL,
  level tinyint(3) DEFAULT NULL,
  url varchar(255) DEFAULT NULL,
  h1 varchar(255) DEFAULT NULL,
  menu varchar(75) NOT NULL,
  title text DEFAULT NULL,
  keywords text DEFAULT NULL,
  description text DEFAULT NULL,
  noindex tinyint(3) DEFAULT NULL,
  access tinyint(3) DEFAULT NULL,
  `virtual` tinyint(3) DEFAULT NULL,
  header text DEFAULT NULL,
  comments tinyint(3) DEFAULT 0,
  slash tinyint(3) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM,
AVG_ROW_LENGTH = 167,
CHARACTER SET utf8,
CHECKSUM = 0,
COLLATE utf8_general_ci;